# Generated by Django 6.0 on 2025-12-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_company_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='passenger_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
