# Generated by Django 4.2.28 on 2026-02-20 07:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('bus_type', models.CharField(choices=[('standard', 'Standard'), ('luxury', 'Luxury'), ('executive', 'Executive')], default='standard', max_length=20)),
                ('total_seats', models.IntegerField(default=48)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='companies.company')),
            ],
            options={
                'verbose_name_plural': 'Buses',
                'db_table': 'buses',
                'ordering': ['-created_at'],
            },
        ),
    ]
